[workspace]
resolver = "2"
members = [
    "packages/*",
    "contracts/factory",
    "contracts/pair",
    "contracts/pair_stable",
    "contracts/pair_concentrated",
    "contracts/pair_astro_xastro",
    "contracts/router",
    "contracts/token",
    "contracts/whitelist",
    "templates/*",
    "contracts/tokenomics/generator",
    "contracts/tokenomics/maker",
    "contracts/tokenomics/staking",
    "contracts/tokenomics/vesting",
    "contracts/tokenomics/xastro_token",
    "contracts/periphery/*",
]

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
strip = true

[workspace.dependencies]
astroport = { version = "2.8", path = "packages/astroport" }
astroport-factory = { version = "1.5", path = "contracts/factory" }

[patch.'https://github.com/astroport-fi/astroport-core']
astroport = { version = "2.8", path = "packages/astroport" }
