[workspace]
resolver = "2"
members = [
    "packages/*",
    "contracts/factory",
    "contracts/pair",
    "contracts/pair_anchor",
    "contracts/lido_converter",
    "contracts/pair_stable",
    "contracts/pair_stable_bluna",
    "contracts/router",
    "contracts/token",
    "contracts/whitelist",
    "contracts/tokenomics/*",
    "contracts/periphery/*"
]

[profile.release.package.astroport-stluna-bluna-lido-converter]
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
incremental = false

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
