[workspace]
resolver = "2"
members = [
    "contracts/factory",
    "contracts/pair",
    "contracts/pair_astro_xastro",
    "contracts/pair_stable",
    "contracts/router",
    "contracts/token",
    "contracts/whitelist",
    "contracts/periphery/*",
    "contracts/tokenomics/*",
    "packages/*",
    "templates/*",
]

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
strip = true
