[package]
name = "astroport-maker"
version = "1.1.1"
authors = ["Astroport"]
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]


[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
library = []


[dependencies]
cosmwasm-std = "1.1"
cw2 = "0.15"
cw20 = "0.15"
cw-storage-plus = "0.15"
ap-maker = { path = "../../../packages/maker" }
astroport = { path = "../../../packages/astroport" }
ap-pair = { path = "../../../packages/pair" }
ap-factory = { path = "../../../packages/factory" }
thiserror = "1.0"
cosmwasm-schema = "1.1"

[dev-dependencies]
astroport-token = { path = "../../token" }
ap-token = { path = "../../../packages/token" }
astroport-factory = { path = "../../factory" }
astroport-pair = { path = "../../pair" }
astroport-pair-stable = { path = "../../pair_stable" }
ap-pair-stable = { path = "../../../packages/pair_stable" }
cw-multi-test = "0.15"
astroport-governance = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "feat/separate_astroport_package" }
ap-escrow-fee-distributor = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "feat/separate_astroport_package" }
astroport-escrow-fee-distributor = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "feat/separate_astroport_package" }
