[package]
name = "astroport-maker"
version = "1.3.1"
authors = ["Astroport"]
edition = "2021"
description = "Astroport Maker"
license = "MIT"
repository = "https://github.com/astroport-fi/astroport"
homepage = "https://astroport.fi"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]


[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = "1.1"
cw2 = "0.15"
cw20 = "0.15"
cw-storage-plus = "0.15"
astroport = { workspace = true }
thiserror = { version = "1.0" }
cosmwasm-schema = "1.1"
astro-satellite-package = { version = "0", git = "https://github.com/astroport-fi/astroport_ibc", branch = "main" }

[dev-dependencies]
astroport-token = { path = "../../token" }
astroport-factory = { path = "../../factory" }
astroport-pair = { path = "../../pair" }
cw-multi-test = "0.15"
astroport-pair-stable = { path = "../../pair_stable" }
astroport-governance = { git = "https://github.com/astroport-fi/astroport-governance", branch = "main" }
astroport-escrow-fee-distributor = { git = "https://github.com/astroport-fi/astroport-governance", branch = "main" }
astroport-native-coin-registry = { path = "../../periphery/native_coin_registry" }
