[package]
name = "astroport-staking"
version = "1.0.1"
authors = ["Astroport"]
edition = "2021"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
library = []


[dependencies]
cosmwasm-std = "1.1"
cw-storage-plus = "0.15"
thiserror = "1.0"
cw2 = "0.15"
cw20 = "0.15"
ap-staking = { path = "../../../packages/staking" }
astroport = { path = "../../../packages/astroport" }
ap-token = { path = "../../../packages/token" }
protobuf = { version = "2", features = ["with-bytes"] }
cosmwasm-schema = "1.1"

[dev-dependencies]
astroport-token = { path = "../../token" }
cw-multi-test = "0.15"
