[package]
name = "astroport-xastro-token"
version = "1.0.1"
authors = ["Astroport"]
edition = "2021"
description = "Expanded implementation of a CosmWasm-20 compliant token for post intialization and saving history"
license = "GPL-3.0-only"
repository = "https://github.com/CosmWasm/cosmwasm-plus"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
ap-xastro-token = { path = "../../../packages/xastro_token" }
astroport = { path = "../../../packages/astroport" }
cw2 = "0.15"
cw20 = "0.15"
cw20-base = { version = "0.15", features = ["library"] }
cw-storage-plus = "0.15"
cosmwasm-std = { version = "1.1", features = ["iterator"] }

[dev-dependencies]
cosmwasm-schema = "1.1"
