[package]
name = "astroport-generator"
version = "2.2.1"
authors = ["Astroport"]
edition = "2021"

exclude = [
    # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
    "contract.wasm",
    "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
library = []


[dependencies]
cosmwasm-std = { version = "1.1" }
cw2 = { version = "0.15" }
cw20 = { version = "0.15" }
cw-storage-plus = "0.15"
cw1-whitelist = { version = "0.15", features = ["library"] }
thiserror = { version = "1.0" }
ap-generator = { path = "../../../packages/generator" }
ap-generator-proxy = { path = "../../../packages/generator_proxy" }
astroport = { path = "../../../packages/astroport" }
ap-pair = { path = "../../../packages/pair" }
ap-factory = { path = "../../../packages/factory" }
ap-vesting = { path = "../../../packages/vesting" }
ap-voting-escrow = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "feat/separate_astroport_package" }
ap-voting-escrow-delegation = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "feat/separate_astroport_package" }
protobuf = { version = "2", features = ["with-bytes"] }
cosmwasm-schema = { version = "1.1" }

[dev-dependencies]
cw-multi-test = "0.15"
astroport-token = { path = "../../token" }
astroport-vesting = { path = "../vesting" }
ap-staking = { path = "../../../packages/staking" }
ap-token = { path = "../../../packages/token" }
ap-pair-stable = { path = "../../../packages/pair_stable" }
astroport-staking = { path = "../staking" }
astroport-factory = { path = "../../factory" }
astroport-pair = { path = "../../pair" }
astroport-pair-stable = { path = "../../pair_stable" }
astroport-whitelist = { path = "../../whitelist" }
anyhow = "1.0"
astroport-governance = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "feat/separate_astroport_package" }
ap-generator-controller = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "feat/separate_astroport_package" }
astroport-generator-controller = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "feat/separate_astroport_package" }
astroport-voting-escrow = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "feat/separate_astroport_package" }
astroport-voting-escrow-delegation = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "feat/separate_astroport_package" }
astroport-nft = { git = "https://github.com/astroport-fi/astroport-governance.git", branch = "feat/separate_astroport_package" }
cw721-base = { version = "0.15", features = ["library"] }

generator-proxy-to-vkr = { git = "https://github.com/astroport-fi/astro-generator-proxy-contracts.git", branch = "main" }
valkyrie = { git = "https://github.com/valkyrieprotocol/contracts.git", rev = "b5fcb666f17d7e291f40365756e50fc0d7b9bf54" }
valkyrie-lp-staking = { git = "https://github.com/valkyrieprotocol/contracts.git", rev = "b5fcb666f17d7e291f40365756e50fc0d7b9bf54" }
valkyrie-vp = { git = "https://github.com/valkyrieprotocol/contracts.git", rev = "b5fcb666f17d7e291f40365756e50fc0d7b9bf54" }
